### ISSUE TITLE
Your model runs with an error！

### ISSUE THREAD

**Issue by QNjeason** [yzhao334/accOpt#1]
运行如下命令时报错
>> A=RobVizLRMate
从 double 转换为 SE3 时出现以下错误:
unknown arguments

出错 RobotObj/buildLRMate (line 62)
            obj.rtb.tool(3,4) = 0.027+0.0157+0.027 + 0.1714;%0.14605;

出错 RobotObj (line 23)
                    obj = obj.buildLRMate;

出错 RobVizLRMate (line 34)
            obj = obj@RobotObj('LRMate');

**Comment by yzhao334** [comment]
Thanks for rising this issue. The newer version of robotic toolbox use SE3 class for transformation instead of numerical matrix as old versions. This bug is fixed in the latest commit.

**Comment by QNjeason** [comment]
Thank you for the code
