### ISSUE TITLE
about the OTG method 

### ISSUE THREAD

**Issue by sunbuny** [yzhao334/accOpt#2]
Hi, really a nice project, I am very curious about the method you used in this project? Could you please give me some detail information. Thank you!

**Comment by yzhao334** [comment]
I was using online trajectory generation (OTG) to generate velocity and acceleration bounded Cartesian space trajectory for robot, then transfer the velocity back into joint space using weighted least square method. For OTG, I was implementing the approach in {"Nonlinear filters for the generation of smooth trajectories.", Zanasi, etc., Automatica, (2000)}. For least square approach you can just follow the code.

Let me know if you have more questions, thanks!

**Comment by sunbuny** [comment]
Thank you for your answer : )
