### ISSUE TITLE
Theory background?

### ISSUE THREAD

**Issue by zhaochenyuangit** [yzhao334/accOpt#3]
Hello, i would appreciate it if you could tell more about the therory background of this OTG algorithm.
Is this an implementation of the _Online Trjectory Generation: Basic Concepts for Instantaneous Reactions to Unforseen Events_ from T. Kroeger in year 2010?

Because I'm a little bit confused that I haven't found any decision tree in the source code about choosing the motion profile.

**Comment by yzhao334** [comment]
Hello, the code is based on a different work: 'Nonlinear filters for the generation of smooth trajectories', R.Zanasi, e.t.c., 2000.    There is no decision tree in this approach, but a global profile designed based on sliding mode control.

Please let me know if you have any other questions. Thanks.

**Comment by zhaochenyuangit** [comment]
Thank you for quick respound! So it's based on another theory, Is it possible to set a bounded jerk by using this "global profile" method? 

Currently I want a Type III OTG planner (defined in the paper mentioned before), which move the robot to the target position (maybe with shortest possible time) with zero velocity, as well as bounded veclocity, acceleration and jerk.

**Comment by yzhao334** [comment]
I see what you need. To the best of my knowledge, you need to pay to get reflexxes lib for Type III planner. Theoretically sliding mode based approach can get what you want, and there is publication. However the information in literature is not enough to reproduce the result by coding. I am not sure whether your initial condition is 0 vel, acc, and jerk? If so, you don't need an 'online' planner and you can use simpler profile. If you really need an online planer, I can share with you a Chinese blog I found recently about this. I haven't got a chance to try the approach so there is no guarantee, but it's worth a try.

**Comment by zhaochenyuangit** [comment]
Thank you! It is good to know that a Type III OTG is not free.
I do need an online planner, for fail-safe planning. The robot may leave the current trajectory at any configuration. However, I can live with that if the jerk is not bounded. In that case I believe a Type I OTG is sufficient. 
And please share the blog with me. 谢谢

**Comment by yzhao334** [comment]
That is good to know. Please check this link: https://zhuanlan.zhihu.com/p/139265234. Thanks.

**Comment by zhaochenyuangit** [comment]
Thanks, I will close this issue.
